### PR TITLE
Update to 1.5.8

### PR DESCRIPTION
**Pull request by mattcg**
Previously at 1.5.3. Note that 1.5.4 fixes a critical vulnerability.

### CODE REVIEW

**Comment by alanivey** [comment]
:+1: - came here to submit the same PR

**Comment by asquelt** [comment]
:+1:

**Comment by asquelt** [comment]
1.5.8 now

**Comment by mattcg** [comment]
Thank you @asquelt. Updated - patch now at 1.5.8.

**Comment by n2aws** [comment]
@mattcg I noticed the README.markdown still references 1.5.3

**Comment by mattcg** [comment]
@palmerit just fixed that. Thank you.

**Pull request closed without merging**
